// mockCourseData.js
export const mockCourseData = {
  aws123: {
    id: 'aws123',
    name: 'AWS Training',
    image: 'https://foundr.com/wp-content/uploads/2021/09/Best-online-course-platforms.png',
    duration: '6 Months',
    students: 350,
    lessons: [
      'Intro to AWS',
      'IAM & EC2',
      'S3 & CloudFront',
      'RDS & DynamoDB',
      'Serverless with Lambda',
      'VPC & Networking',
      'Monitoring & Auto Scaling',
      'Security Best Practices',
      'DevOps with AWS',
      'Capstone Project'
    ],
  },
  angular123: {
    id: 'angular123',
    name: 'Angular 2+',
    image: 'https://foundr.com/wp-content/uploads/2021/09/Best-online-course-platforms.png',
    duration: '4 Months',
    students: 280,
    lessons: [
      'Angular Setup',
      'Components & Modules',
      'Routing & Guards',
      'Forms & Validation',
      'HTTP & Observables',
      'State Management',
      'Testing Angular Apps',
      'Deployment',
    ],
  },
  powerbi123: {
    id: 'powerbi123',
    name: 'PowerBI',
    image: 'https://foundr.com/wp-content/uploads/2021/09/Best-online-course-platforms.png',
    duration: '3 Months',
    students: 420,
    lessons: [
      'Introduction to Power BI',
      'Data Modeling',
      'DAX Fundamentals',
      'Visualizations',
      'Power BI Service',
      'Advanced Analytics',
      'Power BI Security',
      'Real-world Projects'
    ],
  },
  cyber123: {
    id: 'cyber123',
    name: 'Cyber Security',
    image: 'https://foundr.com/wp-content/uploads/2021/09/Best-online-course-platforms.png',
    duration: '5 Months',
    students: 380,
    lessons: [
      'Security Fundamentals',
      'Network Security',
      'Cryptography',
      'Ethical Hacking',
      'Penetration Testing',
      'Security Compliance',
      'Incident Response',
      'Security Operations'
    ],
  },
  azure123: {
    id: 'azure123',
    name: 'Azure',
    image: 'https://foundr.com/wp-content/uploads/2021/09/Best-online-course-platforms.png',
    duration: '6 Months',
    students: 320,
    lessons: [
      'Azure Fundamentals',
      'Azure Compute',
      'Azure Storage',
      'Azure Networking',
      'Azure Databases',
      'Azure Security',
      'DevOps with Azure',
      'Azure Solutions Architect'
    ],
  },
  datasci123: {
    id: 'datasci123',
    name: 'Data Science',
    image: 'https://foundr.com/wp-content/uploads/2021/09/Best-online-course-platforms.png',
    duration: '7 Months',
    students: 450,
    lessons: [
      'Python for Data Science',
      'Statistics Fundamentals',
      'Data Wrangling',
      'Exploratory Data Analysis',
      'Machine Learning Basics',
      'Advanced ML Algorithms',
      'Deep Learning',
      'Big Data Technologies',
      'Data Visualization',
      'Capstone Project'
    ],
  },
  powerapps123: {
    id: 'powerapps123',
    name: 'PowerBI Power Apps Training',
    image: 'https://foundr.com/wp-content/uploads/2021/09/Best-online-course-platforms.png',
    duration: '3 Months',
    students: 210,
    lessons: [
      'Power Apps Fundamentals',
      'Canvas Apps',
      'Model-driven Apps',
      'Power Automate',
      'Connectors',
      'Data Integration',
      'Advanced Techniques',
      'Real-world Projects'
    ],
  },
  salesforce123: {
    id: 'salesforce123',
    name: 'Salesforce Dev & Admin',
    image: 'https://foundr.com/wp-content/uploads/2021/09/Best-online-course-platforms.png',
    duration: '5 Months',
    students: 290,
    lessons: [
      'Salesforce Basics',
      'Object Manager',
      'Security Model',
      'Process Automation',
      'Apex Programming',
      'Visualforce',
      'Lightning Components',
      'Integration',
      'Deployment'
    ],
  },
  devops123: {
    id: 'devops123',
    name: 'DevOps Training',
    image: 'https://foundr.com/wp-content/uploads/2021/09/Best-online-course-platforms.png',
    duration: '6 Months',
    students: 410,
    lessons: [
      'DevOps Fundamentals',
      'Version Control with Git',
      'CI/CD Pipelines',
      'Docker & Containers',
      'Kubernetes',
      'Infrastructure as Code',
      'Monitoring & Logging',
      'Cloud DevOps',
      'Project Work'
    ],
  },
  msbi123: {
    id: 'msbi123',
    name: 'MSBI',
    image: 'https://foundr.com/wp-content/uploads/2021/09/Best-online-course-platforms.png',
    duration: '4 Months',
    students: 180,
    lessons: [
      'SQL Server Basics',
      'SSIS Fundamentals',
      'ETL Processes',
      'SSAS - Multidimensional',
      'SSAS - Tabular',
      'SSRS Reporting',
      'Power BI Integration',
      'Real-world Projects'
    ],
  },
  dataanalytics123: {
    id: 'dataanalytics123',
    name: 'Data Analytics Training',
    image: 'https://foundr.com/wp-content/uploads/2021/09/Best-online-course-platforms.png',
    duration: '5 Months',
    students: 340,
    lessons: [
      'Analytics Fundamentals',
      'SQL for Analytics',
      'Excel Advanced',
      'Python for Analytics',
      'Data Visualization',
      'Statistical Analysis',
      'Predictive Analytics',
      'Business Intelligence',
      'Case Studies'
    ],
  },
  qa123: {
    id: 'qa123',
    name: 'QA / Testing Tools',
    image: 'https://foundr.com/wp-content/uploads/2021/09/Best-online-course-platforms.png',
    duration: '4 Months',
    students: 270,
    lessons: [
      'Testing Fundamentals',
      'Test Planning',
      'Manual Testing',
      'Test Automation Basics',
      'Selenium WebDriver',
      'TestNG/JUnit',
      'API Testing',
      'Performance Testing',
      'Agile Testing'
    ],
  },
  python123: {
    id: 'python123',
    name: 'Python Training',
    image: 'https://foundr.com/wp-content/uploads/2021/09/Best-online-course-platforms.png',
    duration: '4 Months',
    students: 520,
    lessons: [
      'Python Basics',
      'Data Structures',
      'OOP in Python',
      'File Handling',
      'Exception Handling',
      'Modules & Packages',
      'Web Scraping',
      'GUI Development',
      'Python for Automation'
    ],
  },
  selenium123: {
    id: 'selenium123',
    name: 'Selenium Training',
    image: 'https://foundr.com/wp-content/uploads/2021/09/Best-online-course-platforms.png',
    duration: '3 Months',
    students: 310,
    lessons: [
      'Selenium Basics',
      'Locator Strategies',
      'WebDriver',
      'TestNG Integration',
      'Page Object Model',
      'Data-driven Testing',
      'Cross-browser Testing',
      'Selenium Grid',
      'Framework Design'
    ],
  },
  rpa123: {
    id: 'rpa123',
    name: 'RPA Training',
    image: 'https://foundr.com/wp-content/uploads/2021/09/Best-online-course-platforms.png',
    duration: '4 Months',
    students: 230,
    lessons: [
      'RPA Fundamentals',
      'UiPath Basics',
      'Recording & Playback',
      'Data Manipulation',
      'Selectors',
      'Exception Handling',
      'Orchestrator',
      'Advanced Automation',
      'Project Work'
    ],
  },
  genai123: {
    id: 'genai123',
    name: 'Generative AI for Testing',
    image: 'https://foundr.com/wp-content/uploads/2021/09/Best-online-course-platforms.png',
    duration: '3 Months',
    students: 190,
    lessons: [
      'AI Testing Fundamentals',
      'Generative AI Basics',
      'Test Case Generation',
      'Automated Test Maintenance',
      'AI for Test Optimization',
      'Chatbots for Testing',
      'Real-world Applications',
      'Future Trends'
    ],
  },
  dm123: {
    id: 'dm123',
    name: 'Digital Marketing Training',
    image: 'https://foundr.com/wp-content/uploads/2021/09/Best-online-course-platforms.png',
    duration: '4 Months',
    students: 380,
    lessons: [
      'Digital Marketing Basics',
      'SEO Fundamentals',
      'Content Marketing',
      'Social Media Marketing',
      'PPC Advertising',
      'Email Marketing',
      'Analytics & Reporting',
      'Marketing Automation',
      'Strategy Development'
    ],
  },
  appium123: {
    id: 'appium123',
    name: 'Appium',
    image: 'https://foundr.com/wp-content/uploads/2021/09/Best-online-course-platforms.png',
    duration: '3 Months',
    students: 210,
    lessons: [
      'Mobile Testing Basics',
      'Appium Setup',
      'Locator Strategies',
      'Native App Testing',
      'Hybrid App Testing',
      'Parallel Execution',
      'Real Device Testing',
      'Framework Design'
    ],
  },
  playwright123: {
    id: 'playwright123',
    name: 'Playwright',
    image: 'https://foundr.com/wp-content/uploads/2021/09/Best-online-course-platforms.png',
    duration: '2 Months',
    students: 180,
    lessons: [
      'Playwright Basics',
      'Test Automation Setup',
      'Locator Strategies',
      'Page Object Model',
      'Parallel Execution',
      'Visual Testing',
      'API Testing',
      'Framework Design'
    ],
  },
  sdet123: {
    id: 'sdet123',
    name: 'Full Stack QA (SDET)',
    image: 'https://foundr.com/wp-content/uploads/2021/09/Best-online-course-platforms.png',
    duration: '6 Months',
    students: 250,
    lessons: [
      'Programming Fundamentals',
      'Test Automation',
      'API Testing',
      'Performance Testing',
      'Security Testing',
      'CI/CD Integration',
      'Cloud Testing',
      'Framework Architecture',
      'Project Work'
    ],
  },
  jmeter123: {
    id: 'jmeter123',
    name: 'JMeter',
    image: 'https://foundr.com/wp-content/uploads/2021/09/Best-online-course-platforms.png',
    duration: '2 Months',
    students: 160,
    lessons: [
      'Performance Testing Basics',
      'JMeter Setup',
      'Test Plan Creation',
      'Load Testing',
      'Stress Testing',
      'Distributed Testing',
      'Result Analysis',
      'Real-world Scenarios'
    ],
  },
  protractor123: {
    id: 'protractor123',
    name: 'Protractor',
    image: 'https://foundr.com/wp-content/uploads/2021/09/Best-online-course-platforms.png',
    duration: '2 Months',
    students: 140,
    lessons: [
      'Angular Testing Basics',
      'Protractor Setup',
      'Locator Strategies',
      'Page Object Model',
      'Data-driven Testing',
      'Reporting',
      'CI Integration',
      'Best Practices'
    ],
  },
  uft123: {
    id: 'uft123',
    name: 'UFT / QTP',
    image: 'https://foundr.com/wp-content/uploads/2021/09/Best-online-course-platforms.png',
    duration: '3 Months',
    students: 120,
    lessons: [
      'UFT Basics',
      'Record & Playback',
      'VB Scripting',
      'Object Repository',
      'Data-driven Testing',
      'Keyword-driven Testing',
      'Framework Design',
      'Maintenance'
    ],
  },
  cucumber123: {
    id: 'cucumber123',
    name: 'Cucumber',
    image: 'https://foundr.com/wp-content/uploads/2021/09/Best-online-course-platforms.png',
    duration: '2 Months',
    students: 170,
    lessons: [
      'BDD Fundamentals',
      'Gherkin Syntax',
      'Cucumber Setup',
      'Step Definitions',
      'Data Tables',
      'Hooks',
      'Reporting',
      'Integration with Selenium'
    ],
  },
  etl123: {
    id: 'etl123',
    name: 'ETL Testing',
    image: 'https://foundr.com/wp-content/uploads/2021/09/Best-online-course-platforms.png',
    duration: '3 Months',
    students: 150,
    lessons: [
      'ETL Concepts',
      'Data Warehouse Basics',
      'SQL for ETL Testing',
      'Test Data Preparation',
      'Transformation Testing',
      'Data Quality Checks',
      'Performance Testing',
      'Real-world Scenarios'
    ],
  },
  istqb123: {
    id: 'istqb123',
    name: 'ISTQB Training',
    image: 'https://foundr.com/wp-content/uploads/2021/09/Best-online-course-platforms.png',
    duration: '2 Months',
    students: 320,
    lessons: [
      'Testing Fundamentals',
      'Test Design Techniques',
      'Test Management',
      'Tool Support',
      'Static Testing',
      'Test Process',
      'Agile Testing',
      'Exam Preparation'
    ],
  },
  loadrunner123: {
    id: 'loadrunner123',
    name: 'LoadRunner',
    image: 'https://foundr.com/wp-content/uploads/2021/09/Best-online-course-platforms.png',
    duration: '2 Months',
    students: 130,
    lessons: [
      'Performance Testing Basics',
      'LoadRunner Setup',
      'Virtual User Generator',
      'Controller',
      'Analysis',
      'Protocols',
      'Scripting',
      'Real-world Scenarios'
    ],
  },
  webtest123: {
    id: 'webtest123',
    name: 'WebServices Testing',
    image: 'https://foundr.com/wp-content/uploads/2021/09/Best-online-course-platforms.png',
    duration: '2 Months',
    students: 190,
    lessons: [
      'Web Services Basics',
      'SOAP vs REST',
      'Postman',
      'SoapUI',
      'API Test Automation',
      'Security Testing',
      'Performance Testing',
      'Real-world Projects'
    ],
  },
  manual123: {
    id: 'manual123',
    name: 'Manual Testing',
    image: 'https://foundr.com/wp-content/uploads/2021/09/Best-online-course-platforms.png',
    duration: '3 Months',
    students: 280,
    lessons: [
      'Testing Fundamentals',
      'Test Case Design',
      'Defect Life Cycle',
      'Test Documentation',
      'Agile Testing',
      'Mobile Testing',
      'Database Testing',
      'Real-world Projects'
    ],
  }
};

export const courseIdMap = {
  "AWS Training": "aws123",
  "Angular 2+": "angular123",
  "PowerBI": "powerbi123",
  "Cyber Security": "cyber123",
  "Azure": "azure123",
  "Data Science": "datasci123",
  "PowerBI Power Apps Training": "powerapps123",
  "Salesforce Dev & Admin": "salesforce123",
  "DevOps Training": "devops123",
  "MSBI": "msbi123",
  "Data Analytics Training": "dataanalytics123",
  "QA / Testing Tools": "qa123",
  "Python Training": "python123",
  "Selenium Training": "selenium123",
  "RPA Training": "rpa123",
  "Generative AI for Testing": "genai123",
  "Digital Marketing Training": "dm123",
  "Appium": "appium123",
  "Playwright": "playwright123",
  "Full Stack QA (SDET)": "sdet123",
  "JMeter": "jmeter123",
  "Protractor": "protractor123",
  "UFT / QTP": "uft123",
  "Cucumber": "cucumber123",
  "ETL Testing": "etl123",
  "ISTQB Training": "istqb123",
  "LoadRunner": "loadrunner123",
  "WebServices Testing": "webtest123",
  "Manual Testing": "manual123",
};